### ISSUE TITLE
Iphone Waze Dist always showing 'NoRoutes'

### ISSUE THREAD

**Issue by ethanopp** [gcobb321/icloud3#10]
Does something else need to be set up to get the waze sensors working? (TravTime also not showing anything)

Also out of curiosity - how do you have the `driving` sensors working?

**Comment by gcobb321** [comment]
You shouldn’t need to do anything to use Waze  Several other users have reported getting a ‘NoRoutes’ status which indicates some type of error getting data back from Waze. I did make a minor change to that routine to prevent old Waze data from being used later on and moving the device back to a previous location. I’ll take a look at it and see if I see anything. 

If the driving sensor in automation and scripts is what you mean, then it is pretty simple. I use an plan sensor that gets turned on when the zone distance goes over 2 miles and turn it off when I arrive home.

**Comment by ethanopp** [comment]
Awesome would appreciate it! - other that the Waze sensors this component is awesome! Home/Away detection is working like a charm, much better than the countless hours of trying to set up "meta" trackers from various services that I was never able to get perfected :D

**Comment by broyuken** [comment]
I'm having the same issue with the Waze sensors, it shows no route, and my travel time is blank. This is whether I am at home or in another state.

**Comment by gcobb321** [comment]
I may have found the Waze NoRoute issue and hope to nail it down in the next few days after a bunch of testing. The stationary zone may be related. 

If you want to try the fix, download ‘device_tracker_v2.0.5’  [here](https://github.com/gcobb321/icloud3/tree/master/custom_components/icloud3).  Rename your current ‘device_tracker’ in the custom components/iCloud3 directory to save it, then rename the ‘device_tracker_v2.0.5‘ to ‘device_tracker’. 

Restart HA. Let me know if it works.

**Comment by broyuken** [comment]
Just restarted, and they both show blank, but I am also at home. I will be going out later and will see what this reports then.

**Comment by broyuken** [comment]
I just went out to pick up a pizza and it populated history for both sensors so that seems to be fixed. I’m not sure how long I need to be somewhere for the stationary zone to show up but I probably wasn’t there long enough.

**Comment by gcobb321** [comment]
Glad it seemed to work. Stationary zones default to 8 minutes of no movement (override using ‘stationary_still_time’ parameter). Could you do one more thing for me since I’m not at my computer and want to make sure iCloud3 doesn’t crash. I just made another change to the v2.0.5 code to display debug info when checking the iCloud account for contact info. You’ll need to copy, rename and load it like before butAlso  add the ‘log_level: debug’ parameter to the configuration.  It will add messages to the HA log file. If I made an error in the code, coding error messages will be in the log file and can be seen in the ‘Developers tools>log’ screen. Another guy is having problems with his iCloud account and this will help figure out what is going on. iCloud3 will give the errors, if any, when starting. If it starts without errors, you can remove the log_level parameter a and restart HA. Thanks.

**Comment by broyuken** [comment]
Where do I add that to the configuration? to the log card or to the configuration.yaml?

**Comment by gcobb321** [comment]
It would go in configuration.yaml in the device_tracker setup for icloud3 where the username, password, track_devices, etc parameters are. But I’ve already taken care of it so you won’t have to do anything. It was just going to help me make sure v2.0.5 want going to view up before I released it. Thanks anyway.

**Comment by ethanopp** [comment]
Has this been confirmed working? I'm still getting nothing

**Comment by gcobb321** [comment]
Yes, v2.0.5 has been confirmed to to fix this problem. It is available on HACS and the Releases tab above.

**Comment by ethanopp** [comment]
Okay, I had installed this yesterday night and it was still not working - will check again tomorrow once leaving the house...

**Comment by ethanopp** [comment]
@gcobb321 I'm still getting nothing:
![image](https://user-images.githubusercontent.com/11603814/70550684-1eff5f00-1b44-11ea-97f9-f040e4a3b75a.png)

**Update** Apologies - I was being an idiot... can confirm its working.. thanks for the quick turn around!

**Comment by gcobb321** [comment]
Super. Glad it's working now.
