### ISSUE TITLE
ost_event error

### ISSUE THREAD

**Issue by yargok** [gcobb321/icloud3#286]
I am receiving the following error on iCloud3 RC 8:

`name 'ost_event' is not defined`

When rebooting home assistant, a automation call of the locate function works as intended. On subsequent calls, I receive the error above.

**Comment by gcobb321** [comment]
That was fixed on a previous release. See info [here](https://gcobb321.github.io/icloud3_v3_docs/#/chapters/4.3-frequently-asked-questions?id=what-version-of-icloud3-is-running) to see what release you are really running.

**Comment by yargok** [comment]
From HACS, I believe I am running RC8 when I have the error:

<img width="750" alt="image" src="https://github.com/gcobb321/icloud3/assets/741461/aa04e52e-b823-42b3-be43-15a1d79d5d1b">

**Comment by yargok** [comment]
(I appreciate your quick reply)

I tried to redownload the latest version (still looks like above in HACS). When I enter the integration configuration, it appears like i'm running RC6?

<img width="465" alt="image" src="https://github.com/gcobb321/icloud3/assets/741461/ecd91649-7a97-4b25-9996-db164879d185">

**Comment by gcobb321** [comment]
The first screen is a HACS screen from the HACS database and that is what it thinks it has installed. That has nothing to do with what it’s actually running. 

Go back into HACS, select Integration,  put iCloud3 in the search bar and select the one you installed. This may be what you did to get the HACS screenshot. Click 3-dots in upper right, select Update Information. Then do the 3-dots again and redownload and restart HA.

**Comment by yargok** [comment]
Thanks - that is what I tried earlier, and again now. For some reason I
still see version rc6.

**Comment by gcobb321** [comment]
HACS, it seems, keeps picking up old releases. I just deleted the rc6 icloud3.zip file and then deleted the rc6 release. Try doing the update user info and re-download again. HACS uses a GitHub comit number. The one for rc8 is a3f30b2.

**Comment by yargok** [comment]
Yes - I removed it from HACS and my install (verified by going to the config/custom-components directory), followed by a reboot. When I reinstalled icloud3 through HACS, it STILL downloaded the RC6 version.  I need up nuking the directory and manually downloading the zip from GitHub. It now works as expected: it shows as RC8 installed AND I no longer get the ost_event error. 

I'm closing this issues. @gcobb321 - thanks for your help, but it might be worth checking HACS to make sure the right version is uploaded at RC8.

**Comment by gcobb321** [comment]
HA has a code analyzer that runs when a new release is posted to GitHub.  iCloud3 would fail the test process because the analyzer said iCloud3 was dependent on the mobile app, which it is not. Adding it as requiring the mobile app would mean it would not load if the mobile app was not installed. When I was putting up rc7, I found that GitHub assigned the rc6 ID  number to rc7 so when you installed rc7, you would get rc6 code. When I put up rc8, I removed the HA code analyzer but GitHub still assigned the rc7 ID to it. After several retries and release deletions, a new ID was assigned. Somewhere HACS pickled up the old ID number for you while it has the correct ID for others. I’m hoping it is now cleared up.
