### ISSUE TITLE
Setup failed for 'icloud3': Integration not found

### ISSUE THREAD

**Issue by michaelthompson1991** [gcobb321/icloud3#355]
Hi, ive had iCloud3 for a while now and it’s throwing up the following errors https://imgur.com/a/8wgnm16 I also haven’t done anything because ive just came back from holiday today. 

What could the problem be? Also how do I resolve this? 

Also here’s another screenshot https://imgur.com/a/47uFdMo

Thanks!

**Comment by JaviOFC** [comment]
From HASS [2024.7.2 Update's release notes](https://www.home-assistant.io/blog/2024/07/03/release-20247/#202472---july-10): 

[Block icloud3 custom integration from breaking the recorder (](https://github.com/frenck)[@frenck](https://github.com/frenck) - [#121658](https://github.com/home-assistant/core/pull/121658))

https://github.com/home-assistant/core/pull/121658

**Comment by michaelthompson1991** [comment]
Thanks ill have a try in the morning 👍🏻

**Comment by gcobb321** [comment]
See [here](https://github.com/gcobb321/icloud3/issues/355) for a temporary solution to this problem. Scroll to the bottom and follow the instructions to get iCloud3 going again. An update will be released soon.

**Comment by michaelthompson1991** [comment]
Thanks but the link you provided just takes me back to this page of me asking

**Comment by gcobb321** [comment]
Here is what it was suppose to point to. 

iCloud3 inserts special code into the HA recorder that automatically excludes some text based iCloud3 sensors from the HA log database. HA release 3024.7 broke this and 2024.7.2 prevented iCloud3 from loading if it tried to do this injection. 

I am in Switzerland and cannot release an update to iCloud3 to fix this error. However, I have updated the code in GitHub.
1. Download the support/recorder_prefilter.py file in the iCloud3 GitHub repository [here](https://github.com/gcobb321/icloud3_v3/blob/main/custom_components/icloud3/support/recorder_prefilter.py) and save it to the icloud3/support directory. (Look for ‘Raw’ in the menu bar above the code on the right. The Download icon is the 2nd icon to the right)
2. Edit the _icloud3/manifest.json_ file. Change the version value from “3.0.5.2” to “3.0.5.3”. 
3. Restart HA.

The _Event Log_ also adds a large item into the log and will generate a warning message in the Error Log.  To stop the warning message and exclude this sensor from being added, add the following to the _configuration.yaml_ file.  It adds a manual exclude for sensor. 

```
recorder:
  exclude:
    entities:
      - sensor.icloud3_event_log
```

**Comment by michaelthompson1991** [comment]
Thanks!

**Comment by gcobb321** [comment]
iCloud3 v3.0.5.5 (7/16/2024) has been released that fixes this problem. It should be available on HACS in a day or so. No other changes have been made.

**Comment by michaelthompson1991** [comment]
No problem, that's great thanks! Thank you for the hard work!

**Comment by michaelthompson1991** [comment]
I've downloaded the update but it still says not loaded in the devices and services part of HA, am I missing something? Also I still have a notification saying The following integrations and platforms could not be set up:

icloud3 (Show logs)
Please check your config and logs.
4 minutes ago

**Comment by gcobb321** [comment]
I assume you restarted HA. Try restarting again. Maybe that will clear the cache.

**Comment by michaelthompson1991** [comment]
Yeah I restarted then rebooted HA and still nothing 🤔

**Comment by michaelthompson1991** [comment]
Shall I try redownloading from HACS or will that cause more problems?

**Comment by michaelthompson1991** [comment]
This is what it says when I open the logs https://imgur.com/a/OfAHgmg

**Comment by gcobb321** [comment]
Don't use HACS. It probably has not done the scan yet and will pick up v3.0.5.2. The zip file with v3.0.5.5 is on the releases page [here](https://github.com/gcobb321/icloud3_v3/releases).

Here is another copy of it.

[icloud3.zip](https://github.com/user-attachments/files/16252865/icloud3.zip)

**Comment by michaelthompson1991** [comment]
So shall I just wait then? I'm busy tonight anyway so I can get back onto it tomorrow if that's easier?

**Comment by gcobb321** [comment]
HACS was the problem. It was downloading the v3.0.5.2 release, not the v3.0.5.5 release even though the zip file for the release was correct and the files were correct. I will create a new release and see what happens.

Here is the v3.0.5.5 zip file.
[icloud3.zip](https://github.com/user-attachments/files/16253192/icloud3.zip)

**Comment by michaelthompson1991** [comment]
No problem, thanks. What do I do with the zip file? Shall I just wait for the new release you post?

**Comment by gcobb321** [comment]
It was my error. I did everything except update the _custom_components/icloud3_ code files on the GitHub repository so it was picking up v3.0.5.2 code instead. 

All is good now. HACS updates the files  with the v3.0.5.5 version after refreshing via the _Update Information_ option.

**Comment by michaelthompson1991** [comment]
No problem, I’ll give it a try when I get home 👍🏻Sent from my iPhoneOn 16 Jul 2024, at 17:22, Gary Cobb ***@***.***> wrote:﻿
It was my error. I did everything except update the custom_components/icloud3 code files on the GitHub repository so it was picking up v3.0.5.2 code instead.
All is good now. HACS updates the files  with the v3.0.5.5 version after refreshing via the Update Information option.

**Comment by michaelthompson1991** [comment]
I have the download ready and waiting to do when I get home, will keep you updated 👍🏻

**Comment by michaelthompson1991** [comment]
It's now working, thanks for the amazing support!

**Comment by gcobb321** [comment]
Completed with iCloud3 v3.0.5.5/v3.0.5.6
