### ISSUE TITLE
can't get icon back for device tracker 

### ISSUE THREAD

**Issue by petep0p** [gcobb321/icloud3#412]
hello! I've just installed this integration after getting annoyed with the official one and it's worlds better! 

only 1 minor issue I'm running into: i configured my devices to use pictures (which say they're in /local/icloud3/XX.png but that doesn't seem to be a path that's really there on my system), but i would like to change them to just use the standard icon instead. i went through the reconfiguration of the device, and selected "none" for the picture, but the picture still displays. i confirmed the setting took (meaning when i try to reconfigure again, it's already set to "none"). (restarting afterward does not change the setting at all)

is there another way to fix this?

**Comment by gcobb321** [comment]
I think this is fixed in the update I am working on now. I have a few other issues I’m working on before I release it but it shouldn’t be too long. 

The _/local_  directory has always equated to _/config/www_ on HA as far as I know. I’d that where your .png image files are?

**Comment by petep0p** [comment]
ah, yes, i can see them in /config/www/icloud3/
Thanks for getting back, and i'll wait for the next release.

**Comment by gcobb321** [comment]
I believe this is fixed in v3.1.4.4. Reopen if you still have an issue.

**Comment by petep0p** [comment]
So.... it looks like, for me anyway, i still can't get rid of the picture. What i'm specifically talking about is the device_tracker pic. I have reset it to "None" in the picture field, but it still shows up as the device_tracker image. I am able to turn on/off the pic-vs-icon for the Watch Badge,  but not for the device_tracker.
The device_tracker is specifically the only entity that shows up under "Diagnostic"

any help is appreciated. thanks!!

ps - i don't seem to have permission to reopen this issue.

**Comment by gcobb321** [comment]
@petep0p 
I thought I had fixed the icon issue a while back, but I guess not. 

This will assign the default icons to the device based on the device type. I'm going to think about letting you select the 'mdi:' file to be assigned to a device instead of the picture. Then you could set a different icon for each device. I'll send you a test version to check it out.

This should fix the icon issue. Unzip the file into the \icloud3 directory and restart HA.

[patch-icon-fix v3.1.4.4.zip](https://github.com/user-attachments/files/18522993/patch-icon-fix.v3.1.4.4.zip)

**Comment by petep0p** [comment]
@gcobb321 thanks!! i unzipped that file and overwrote the existing ones of the same names in `/config/custom_components/icloud3/` and the icon is back after a restart of HA. thanks for getting it worked out!

**Comment by gcobb321** [comment]
I just uploaded v3.1.5b3 Beta 3 and have added the ability to select the Device's icon from the HA icon _mdi:_ image list. The default icon is 'mdi:account' instead of one based on the Device Type.

Go [here](https://github.com/gcobb321/icloud3/issues/384#issuecomment-2628161160) to get it and see the current Release Notes.

**Comment by petep0p** [comment]
👍👍🙌🫶
