### ISSUE TITLE
Issues with Apple's changed authentication

### ISSUE THREAD

**Issue by DBa2016** [gcobb321/icloud3#51]
Since Apple changed something in their iCloud authentication, this component stopped working for me (as many others, too). This was originally blamed to HA 0.94, but that was a coincidence only.

Creating this issue to track our progress on getting this working again. This is also related to https://github.com/picklepete/pyicloud/issues/206.

So far, I got it kind of working (with one very annoying side effect), by doing the following:
1) in the HA pyenv, replaced "pyicloud" with a modified version from @PeterHedley94 and @danielfmolnar by executing following:
```
pip uninstall pyicloud
pip install git+https://github.com/danielfmolnar/pyicloud

```
2) in device_tracker.py, I manually replaced occurences of "requires_2fa" by "requires_2sa" (I will add some mitigating code to this file to be able to deal with both cases without throwing an exception and create a PR, probably later today).

This got me a working component (after rea-authentication), **BUT**: on irregular schedule, about every 30-40 minutes, I get a re-authentication request on my i-devices. This does not prevent the component from working, but it is very annoying.

**Comment by gcobb321** [comment]
As you know, I’ve been working on this for a week or so and am finalizing it now. I will have a special pyicloud-ic3 version that will be available in the iCloud3 repository. It will be a consolidate all pyicloud code in one file and no special PIP commands will be needed to install it other than copying it to the icloud3 custom_components directory. Users who are not as familiar with Linux commands would have a difficult time doing it and it would be a support nightmare. 

 There are also some things missing from peterhedley94’s version regarding 2sv tokens which I have added. He and I have been in touch. 

Don’t bother with a PR for the device_tracker.py. It has been fixed and will be rejected. 

The notification that pops up every eo minutes or so is from apple saying that your account has been logged into and gives you a token (as you know). iCloud does not support storing trust tokens on Linux computers if 2fa is being used for an account, which is the basic problem. 

I have stopped these messages by creating another iCloud account (with another email address). And authorizing find my friends to locate the real account that is being used for the phone. Then in iCloud3, use that account. Right now, I also have family sharing set up for the ha account, which I want to turn off for security purposes since 2fa is not used. 

There is still one bug left that was in the original code I came across dealing with changing an iCloud account password while HA is Running. Since the account is authenticated every time the device is polled and HA has the old password, pyicloud crashes and takes everything with it with an lunknown error message that I thought I’d fix.

**Comment by DBa2016** [comment]
Okay, just wanted to help here :)

**Comment by gcobb321** [comment]
I'll let you know when I put it out so you can try it out. Try setting up the second iCloud account with just the fmf pointing to several devices. It should work with the code you have now since the 2sv token approach is only needed if 2fa is set up on an account. 

That would make the stuff I'm doing not really needed (just figured that out yesterday). But my new code still needed to be done to stop the crashes. 

And thanks for doing some digging and suggestions. Since I'm in the middle of iCloud3, rather than doing a PR, it would be better to open an issue and include the code changes. It will make it easier on me keeping up with the base code on my system, which is not tied to my github repository until it's ready.

**Comment by DBa2016** [comment]
Hmmm - I created a secondary icloud account and added the primary to friends, so the devices should be trackable... Now how would I see the primary accounts devices in icloud3?...

**Comment by gcobb321** [comment]
Real account Id is garyreal@gmail.com.
Other account (without 2fa) is geekstergary@gmail.com. It will follow garyreal@gmail.com in fmf.
Device name is gary_iphone. It will log into iCloud in the settings with garyreal@gmail.com 
Device_tracker.yaml will have username: geekstergary@gmail.com. 

iCloud3 will log into the geekstergary account and find the friends associated with it, hopefully. I know it will work if geekstergary has set up a family group with garyreal  in it but, in order to have family sharing, you have to put in a credit card. I don’t think you have to if you just use the fmf without family sharing  

Try those scenarios and see if it works while I chew on the other approach.

**Comment by DBa2016** [comment]
Does not work, unfortunately - pyicloud does not support fmf (there was a PR to add this support 2 years ago but it was never merged...)

**Comment by gcobb321** [comment]
Thanks. Let me see what I can do to add this to the special version of pyicloud I’m working with.

————————
Gary Cobb

**Comment by gcobb321** [comment]
FYI-I have the fmf code you found merged into the special pyicloud module I’m working with and have accessed the data in a test mode by iCloud3. I’m now in the process of recoding some of the routines to be able to import data from fmf, iCloud, the iOS app v1.5 or iOS app v2.0 based on some new configuration parameters. A new configuration Parameter (fmf_friends_email) will tie the device name to the friends to be tracked. 

Again, thanks for bringing the fmf code to my attention. I’ll put a beta on the repository for you when it’s ready.

**Comment by DBa2016** [comment]
Good job, Gary!
Please do let me know if you need help :)

**Comment by gcobb321** [comment]
iCloud3 v1.1.0 has been updated to track devices with FmF.  [Go here](https://github.com/gcobb321/icloud3/tree/master/beta) for the modules (device_tracker.py & pyicloud_ic3.py). The ChangeLog lists the 'breaking changes' and how to set it up. Let me know if you see anything wierd or it it seems to work fine.

I haven't tested it with multiple accounts being used at the same time but don't expect any issues.
Gary

**Comment by klovatt** [comment]
Looking forward to trying this.

Using FmF will be a more secure way of handling devices from multiple users as we will no longer have to collect their iCloud credentials.

**Comment by DBa2016** [comment]
Great job! First try was unsuccessful though for me, iCloud3 does not get the device information ("Not Tracking (FmF) icloud3/<my-device-name>/None"), need to dig further into it.

**Comment by gcobb321** [comment]
The Not Tracking message is in the format of:
     account/devicename/emailaddress
so the track)devices should be:
```
realdevicename > fmfaccountemailaddress, badgepicture.png
```
Example:
   ```
gary_iphone > gary456@gmail.com, gary.png
my phone is logged into icloud using gary456@gmail.com (the one with 2fa)
Gary_iphone (gary_iphone) is the name that device in General>Settings>about
```
I'll add a logging stmt to show what the exact yaml file is. Will update it in a few minutes

**Comment by gcobb321** [comment]
There is one other thing I omitted from the instructions.

FmF uses an ID code ("MTg2Djk7ODEq") to identify contacts (friends) with the location data. During initialization, iCloud3 matches the email address in the devicename's tracked_devices parameter with the email address in the FmF accounts contacts/friends record to tie the FmF ID code to the devicename. You have to set up a contact in the Contacts App while logged into the FmF iCloud account. If you don't, error messages are displayed during initialization and no devices will be tracked.

The minimum amount of information you need to enter into the Contacts app is the First Name, Last Name and email address.

**Comment by gcobb321** [comment]
I've just updated iCloud to v1.1.0 beta 2. [Get it here ](https://github.com/gcobb321/icloud3/tree/master/beta)

**Comment by OppyLock** [comment]
Is there any reason that this can't use the app-specific passwords feature of icloud?  
It seems designed for exactly this sort of use.

**Comment by gcobb321** [comment]
I also thought it would be a good Thing to use but could never get it to work  I think it might be related to difference in how an app logs in vs how a program logs in.

————————
Gary Cobb

**Comment by gcobb321** [comment]
I've just updated iCloud to v1.1.0 beta 3. [Get it here ](https://github.com/gcobb321/icloud3/tree/master/beta). 

- It corrects crashes if the username/password are invalid
- Added a new *base_zone* parameter to select a zone other than the 'home' zone to be used as the basis for distance and time calculations.
- Changes the way a day number is displayed to see if iCloud3 will run under Windows
- Displays a warning if the *track_devices* parameter is configured incorrectly.
- Verified that Find-my-Friends works when it has several platforms in the device_trackers configuration file all logged into the same or different icloud accounts. For example:
  - Platform: icloud3, username: geekstergary@gmail.com, password: pw, accountname: gkstr1, track_devices: gary_iphone
   - Platform: icloud3, username: geekstergary@gmail.com, password: pw, accountname: gkstr2, track_devices: lillian_iphone
  - Platform: icloud3, username: jonny890@gmail.com, password: pw, accountname: jonny, track_devices: jonny_ipad

The *device_tracker.py* file and the *pyicloud_ic3.py* file were updated.

**Comment by klovatt** [comment]
I've gievn this a go, and now have good results.

I now use one fmf account to track devices from four different people. Previously I used four icloud accounts, so now I can give them back their credentials.
I also set up a secondary tracker with the same fmf account with a different home.

Interesting discoveries along the way:
1. Loading this new version caused new authentication popups on devices configured to use icloud from the previous version, and then the popus gave the confirmation codes. Hassio did not prompt for the codes, so those devices stopped working.
2. Don't create the icloud account from IOS 13 (beta). It automatically enables 2fa, and it cannot be turned off. Creating it from the appleid web site works just fine.
3. After your friend/family member/whatever starts sharing their location (remember to have that contact set up first or it doesn't work), give it a while (I found an hour was reliable) to make sure everythng syncs between your device and the icloud servers.
4. If you use the same device name for each device tracker in my "two homes" scenario, things work, but you cannot rely on presence to trigger activities as the presence values alternate between the two homes. I got around this by giving a different device name for the second instance.
5. Device names don't have to match the real device names for this component. We are now tracking the person using whichever device they choose. However, the hassio icloud component probably cares, so I don't know if my workaround in point 4 is valid.

**Comment by DBa2016** [comment]
Hmmm - seems like I am too stupid for this...
1) created a "side" icloud account, set up FmF with my main account (FmF permission and added contact)
2) downloaded beta3 icloud3 code to the right location (same issues with Beta2)
3) following is the error output (filtered by "icloud"):
```tail: /home/hass/.homeassistant/home-assistant.log: file truncated
2019-07-15 23:43:48 INFO (SyncWorker_11) [homeassistant.loader] Loaded icloud3 from custom_components.icloud3
2019-07-15 23:43:49 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for icloud3 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-07-15 23:43:50 INFO (SyncWorker_4) [custom_components.icloud3.device_tracker] Setting up iCloud3 v1.1.0b3 device tracker for xxx@xxx.com/icloud3, using device_tracker.legacy code
2019-07-15 23:43:50 INFO (SyncWorker_4) [custom_components.icloud3.device_tracker] Zone Name Table Initialized {'*****}, Base Zone 'home'
2019-07-15 23:43:50 INFO (SyncWorker_4) [custom_components.icloud3.device_tracker] Verifying Waze Route Service component
2019-07-15 23:43:50 INFO (SyncWorker_4) [custom_components.icloud3.device_tracker] Waze Route Service not available
2019-07-15 23:43:50 INFO (SyncWorker_4) [custom_components.icloud3.device_tracker] Waze Settings: Region=EU, Realtime=False, MaxDistance=1609.35, MinDistance=1.61
2019-07-15 23:43:50 INFO (SyncWorker_4) [custom_components.icloud3.device_tracker] iCloud3 Initalization, Stage 1, Verify iCloud Location Service
2019-07-15 23:43:50 INFO (SyncWorker_4) [custom_components.icloud3.device_tracker] iCloud3 Tracking Method: Find My Friends
2019-07-15 23:43:50 INFO (SyncWorker_4) [custom_components.icloud3.device_tracker] Requesting authorization for xxx@xxx.com/icloud3
2019-07-15 23:43:50 INFO (SyncWorker_4) [custom_components.icloud3.pyicloud_ic3] Authenticating as xxx@xxx.com
2019-07-15 23:43:56 INFO (SyncWorker_4) [custom_components.icloud3.pyicloud_ic3] Authentication completed successfully
2019-07-15 23:43:56 INFO (SyncWorker_4) [custom_components.icloud3.device_tracker] Authentication for xxx@xxx.com/icloud3 successful
2019-07-15 23:43:56 INFO (SyncWorker_4) [custom_components.icloud3.device_tracker] iCloud3 Initalization, Stage 2, Set up tracked devices
2019-07-15 23:43:56 INFO (SyncWorker_4) [custom_components.icloud3.device_tracker] Initializing Device Tracking for user xxx@xxx.com
2019-07-15 23:43:56 INFO (SyncWorker_4) [custom_components.icloud3.device_tracker] Matching devicenames with FmF contact emails
2019-07-15 23:43:57 INFO (SyncWorker_4) [custom_components.icloud3.device_tracker] Matched [iwatchname] with FmF contact [contact_first_name]/real_acc@icloud.com
2019-07-15 23:43:57 INFO (SyncWorker_4) [custom_components.icloud3.device_tracker] Tracking (FmF) icloud3/[iwatchname]/real_acc@icloud.com
2019-07-15 23:43:57 INFO (SyncWorker_4) [custom_components.icloud3.device_tracker] Tracking Devices [iwatchname]
2019-07-15 23:43:57 INFO (SyncWorker_4) [custom_components.icloud3.device_tracker] iCloud3 Initalization, Stage 3, Setting up icloud3/[iwatchname]
2019-07-15 23:43:57 INFO (SyncWorker_4) [custom_components.icloud3.device_tracker] [contact_first_name](watch) Created Stationary Zone, GPS=(90, 180)
2019-07-15 23:44:00 INFO (SyncWorker_3) [custom_components.icloud3.device_tracker] [contact_first_name](watch) Updating, iCloud3 Restart not completed, will retry location update
2019-07-15 23:44:00 INFO (SyncWorker_3) [custom_components.icloud3.pyicloud_ic3] Authenticating as xxx@xxx.com
2019-07-15 23:44:03 INFO (SyncWorker_3) [custom_components.icloud3.pyicloud_ic3] Authentication completed successfully
2019-07-15 23:44:03 ERROR (SyncWorker_3) [custom_components.icloud3.device_tracker] ►►INTERNAL ERROR-RETRYING (_update_device_icloud/OverallUpdate-'NoneType' object is not iterable)
2019-07-15 23:44:03 ERROR (SyncWorker_3) [custom_components.icloud3.device_tracker] 'NoneType' object is not iterable
  File "/home/hass/.homeassistant/custom_components/icloud3/device_tracker.py", line 2109, in _setup_data_fmf
  File "/home/hass/.homeassistant/custom_components/icloud3/device_tracker.py", line 2202, in _refresh_fmf_location_data
  File "/home/hass/.homeassistant/custom_components/icloud3/device_tracker.py", line 1821, in _update_device_icloud
  File "/home/hass/.homeassistant/custom_components/icloud3/device_tracker.py", line 2116, in _setup_data_fmf
  File "/home/hass/.homeassistant/custom_components/icloud3/device_tracker.py", line 2202, in _refresh_fmf_location_data
2019-07-15 23:44:03 INFO (SyncWorker_3) [custom_components.icloud3.device_tracker] [contact_first_name](watch) Zone Change Detected, From=not_set, To=not set
2019-07-15 23:44:03 INFO (SyncWorker_3) [custom_components.icloud3.device_tracker] [contact_first_name](watch) Updating, FmF Update via NextUpdtTime
2019-07-15 23:44:04 INFO (SyncWorker_3) [custom_components.icloud3.pyicloud_ic3] Authenticating as xxx@xxx.com
2019-07-15 23:44:06 INFO (SyncWorker_3) [custom_components.icloud3.pyicloud_ic3] Authentication completed successfully
2019-07-15 23:44:07 ERROR (SyncWorker_3) [custom_components.icloud3.device_tracker] ►►INTERNAL ERROR-RETRYING (_update_device_icloud/OverallUpdate-'NoneType' object is not iterable)```

**Comment by gcobb321** [comment]
@DBa2016 It looks like the FmF account was authorized but then failed to locate the watch afterwards during the initial setup. It died in the routine doing reauthentication 14-seconds earlier extracting the data it assumed would be available. The next statement was to issue an error message that no location data was was found and iCloud3 was aborting. I'll put some error checking in the refresh_data_routine that better explains what is going on. 

Did you open the FmF app and, as a final check, verify that you can locate the watch after you set it up? I should probably add that as the last step of thegetting started instructions.

**Comment by DBa2016** [comment]
> Did you open the FmF app and, as a final check, verify that you can locate the watch after you set it up? I should probably add that as the last step of thegetting started instructions.

Will do that later today when I get home and report results! Thanks for the analysis!

**Comment by DBa2016** [comment]
I verified this - you were indeed right, the FmF account for some reason did not have the permission to track the main account. After requesting and granting the permission, it magically started working :)

Following point should be mentioned in the documentaion (I can raise a PR for this once you decide to deploy this code into the production version):
- only one device is tracvked per "main" account; this is not a significant restriction, but worth noting if you are tracking "devices" and not "persons"
- the device name ("gary_iphone" in your config example) is used as the entity id (good to know for creating automations etc.). It does not have to match the real device name
- the device name must not contain hyphens - underscores are fine though. Hyphens result in "internal error" on every update (`►►INTERNAL ERROR (UpdtSensorUpdate-Invalid entity id encountered: sensor.name-with-hyphens_interval. Format should be <domain>.<object_id>`)

Did not figure out yet which device is actually being tracked, this is on my to-do list.

**Comment by gcobb321** [comment]
1. Yes, You are tracking devices, not people but typically, each person has there own device. And the person is third to the main account using their iCloud acc I'd (email address).
2. Yes, the device name does not have to match the team device name. But if it doesn't, the ha ios app and the device being tracked are no longer tied together so zone exit and enter notifications will not be picked up for the device by iCloud3.
3. I already strip spaces from the device name. I'll convert dashes and other special characters to underscores. I thought it was obvious in discussing the sensors that the device name will be part of the sensor entity name.

**Comment by klovatt** [comment]
Now running beta 4.

It seems the fix for devices in multiple groups being polled at 5 second intervals is fixed, thanks!

Now, the next observation:
I have a card which uses device_tracker.iPhone_name

I normally just click on this to see the details, rather than have explicit entries in cards. Right now it is using the details from the second group (using base_zone). This means I don't have visibility to the details from the polling referencing the home zone.

I imagine at some point the details would switch depending on which scan was most recent.

All the details are available via sensors, so this is not a showstopper in my opinion. I suppose this is something to live with.

**Comment by gcobb321** [comment]
That 5-second repoll was a tough one to find and then fix. Even after I realized that the home zone would change the device_tracker attributes which would get picked up by the other zone as a change which would change it again, and-so-on.. Then to find a way to communicate between instances and still have an iosapp trigger work.

Yes, the device_tracker attributes are the last zone polled but the sensors report everything when the zone is updated.

For testing, I have 2 zones set up for me and 2 for myself with the same devicename and am having no issues. I have one card for myself with both zones side by side using the sensors to show info for both zones at the same time. You could set up a card that would just show info you want for both zones instead of hitting details. But you already know that.

Attached is my lovelace setup for 2 zones.

[ui-lovelace-gary-2-zones.txt](https://github.com/gcobb321/icloud3/files/3414725/ui-lovelace-gary-2-zones.txt)

btw, I fixed another bug dealing with stationary zone data not being set up this morning. And I am, once again, changing the distance sensor and device_attribute from "home_distance" to "zone_distance". It as just getting too confusing  explaining in the docs and elsewhere that the home_distance was not really the home_distance when dealing with other base_zones.

Wil be updated to beta5 in a few hours.

**Comment by gcobb321** [comment]
I think beta 6 or 7 solves everything.
