### ISSUE TITLE
IOS v2 tracking method with 2.0rc-a

### ISSUE THREAD

**Issue by manonstreet** [gcobb321/icloud3#72]
I'm unable to utilize the iosapp2 tracking method with the most current beta.  When using the same configuration with 1.08b, everything works as expected, however upgrading to 2.0rc-a results in failure.

The logs are as follows (timestamps removed for readability):

1.08b
```INFO (MainThread) [homeassistant.components.device_tracker] Setting up device_tracker.legacy
INFO (SyncWorker_17) [custom_components.icloud3.device_tracker] Setting up iCloud3 v1.1.0b8 device tracker for <redacted>@gmail.com:family:home, using device_tracker.legacy code
ERROR (SyncWorker_17) [custom_components.icloud3.device_tracker] _____ zones=['zone.home']
INFO (SyncWorker_17) [custom_components.icloud3.device_tracker] Zone Name Table Initialized {'home': 'Home'}, Base Zone 'home'
INFO (SyncWorker_17) [custom_components.icloud3.device_tracker] Verifying Waze Route Service component
INFO (SyncWorker_17) [custom_components.icloud3.device_tracker] Waze Settings: Region=US, Realtime=False, MaxDistance=1609.35, MinDistance=1.61
INFO (SyncWorker_17) [custom_components.icloud3.device_tracker] iCloud3 Initalization, Stage 1, Verify iCloud Location Service
INFO (SyncWorker_17) [custom_components.icloud3.device_tracker] iCloud3 Tracking Method: IOS App Version 2
INFO (SyncWorker_17) [custom_components.icloud3.device_tracker] iCloud3 Initalization, Stage 2, Set up tracked devices
INFO (SyncWorker_17) [custom_components.icloud3.device_tracker] Initializing Device Tracking for user <redacted>@gmail.com:family
INFO (SyncWorker_17) [custom_components.icloud3.device_tracker] Tracking (IOS App v2) maximus:family, <redacted>@gmail.com
INFO (MainThread) [homeassistant.setup] Setup of domain mobile_app took 0.3 seconds.
INFO (SyncWorker_17) [custom_components.icloud3.device_tracker] Tracking Devices maximus (_3)
INFO (SyncWorker_17) [custom_components.icloud3.device_tracker] iCloud3 Initalization, Stage 3, Setting up maximus.family
INFO (SyncWorker_17) [custom_components.icloud3.device_tracker] maximus:family(None) Created Stationary Zone
INFO (MainThread) [homeassistant.components.notify] Setting up notify.mobile_app
INFO (SyncWorker_17) [custom_components.icloud3.device_tracker] iCloud3 Initalization, Stage 4, Locating devices
INFO (MainThread) [homeassistant.components.device_tracker] Setting up device_tracker.mobile_app
```

2.0rc-a:
```
INFO (MainThread) [homeassistant.components.device_tracker] Setting up device_tracker.legacy
INFO (SyncWorker_5) [custom_components.icloud3.device_tracker] Setting up iCloud3 v2.0rc-a device tracker for User: <redacted>@gmail.com, Group: family, using device_tracker.legacy code
INFO (SyncWorker_5) [custom_components.icloud3.device_tracker] Verifying Waze Route Service component
INFO (SyncWorker_5) [custom_components.icloud3.device_tracker] Waze Settings: Region=US, Realtime=False, MaxDistance=1609.3470878864446, MinDistance=1.6093470878864444
INFO (SyncWorker_5) [custom_components.icloud3.device_tracker] iCloud3 v2.0rc-a Initalization > Stage 1, Verify iCloud Location Service
INFO (SyncWorker_5) [custom_components.icloud3.device_tracker] iCloud3 Tracking Method: None
INFO (SyncWorker_5) [custom_components.icloud3.device_tracker] iCloud3 v2.0rc-a Initalization > Stage 2, Setting up tracked devices
INFO (SyncWorker_5) [custom_components.icloud3.device_tracker] Decoding track_devices <maximus > <redacted>@gmail.com, 3>
INFO (SyncWorker_5) [custom_components.icloud3.device_tracker] Not Tracking (None) > maximus (<redacted>@gmail.com)
INFO (SyncWorker_5) [custom_components.icloud3.device_tracker] IOS App v2 monitoring > device_tracker.maximus_3, sensor.maximus_last_update_trigger
ERROR (SyncWorker_5) [custom_components.icloud3.device_tracker] Error: iCloud3 setup aborted for group 'family', no devices to track
INFO (MainThread) [homeassistant.components.device_tracker] Setting up device_tracker.mobile_app
```

Relevant configuration information:

device_tracker.yaml (included via configuration.yaml):
```
- platform: icloud3
  username: !secret icloud_username
  password: !secret icloud_password
  group: family
  tracking_method: iosapp2
  track_devices:
    - maximus > <redacted>@gmail.com, 3
```

known_devices.yaml:
```
maximus:
  name: Maximus
  track: true
  hide_if_away: false
```

It's not clear if this is a bug in the latest release candidate, or if this is a configuration error.

**Comment by gcobb321** [comment]
The 'tracking_method' was changed to automatically detect the version of 
the HA IOS app that is installed. Change 'iosapp2' to 'iosapp' and see 
if that corrects the problem.

------ Original Message ------

**Comment by manonstreet** [comment]
Progress!

We now get to stage 4:
```
INFO (SyncWorker_7) [custom_components.icloud3.device_tracker] Setting up iCloud3 v2.0rc-a device tracker for User: <redacted>@gmail.com, Group: family, using device_tracker.legacy code
INFO (MainThread) [homeassistant.components.scene] Setting up scene.homeassistant
INFO (SyncWorker_7) [custom_components.icloud3.device_tracker] Verifying Waze Route Service component
INFO (SyncWorker_7) [custom_components.icloud3.device_tracker] Waze Settings: Region=US, Realtime=False, MaxDistance=1609.3470878864446, MinDistance=1.6093470878864444
(SyncWorker_7) [custom_components.icloud3.device_tracker] iCloud3 v2.0rc-a Initalization > Stage 1, Verify iCloud Location Service
(SyncWorker_7) [custom_components.icloud3.device_tracker] iCloud3 Tracking Method: IOS App
(SyncWorker_7) [custom_components.icloud3.device_tracker] iCloud3 v2.0rc-a Initalization > Stage 2, Setting up tracked devices
(MainThread) [homeassistant.setup] Setup of domain automation took 0.1 seconds.
(SyncWorker_7) [custom_components.icloud3.device_tracker] Decoding track_devices <maximus > <redacted>@gmail.com, 3>
(SyncWorker_7) [custom_components.icloud3.device_tracker] Tracking (IOSApp) > maximus (<redacted>@gmail.com)
(SyncWorker_7) [custom_components.icloud3.device_tracker] IOS App v2 monitoring > device_tracker.maximus_3, sensor.maximus_last_update_trigger
(MainThread) [homeassistant.setup] Setup of domain scene took 2.6 seconds.
(SyncWorker_7) [custom_components.icloud3.device_tracker] Tracking Devices >  maximus (_3)
(MainThread) [homeassistant.setup] Setup of domain hassio took 0.9 seconds.
(SyncWorker_7) [custom_components.icloud3.device_tracker] iCloud3 v2.0rc-a Initalization > Stage 3, Setting up maximus
(MainThread) [homeassistant.setup] Setup of domain switch took 0.2 seconds.
(SyncWorker_7) [custom_components.icloud3.device_tracker] Stationary Zone Created > maximus_stationary
(SyncWorker_7) [custom_components.icloud3.device_tracker] iCloud3 v2.0rc-a Initalization > Stage 4, Locating devices
(MainThread) [homeassistant.setup] Setup of domain device_tracker took 1.3 seconds.
```
However, some different errors now appear:
```
INFO (SyncWorker_5) [custom_components.icloud3.device_tracker] maximus(None) Device Tracking Complete, Results-BaseZone-home > Zone-home, GPS-(<redacted>, <redacted>), Interval-2 hrs, Dist-0 mi, TravTime- (in_zone), NextUpdt-2:53:15, Located-4:53:01 (-14381 sec ago)
ERROR (SyncWorker_5) [custom_components.icloud3.device_tracker] name 'iosapp_version_no' is not defined
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 1727, in _update_device_iosapp_trigger
    event_msg = ("IOS App v{} update complete").format(iosapp_version_no)
NameError: name 'iosapp_version_no' is not defined
ERROR (SyncWorker_5) [custom_components.icloud3.device_tracker] ►►INTERNAL ERROR-RETRYING (_update_device_ios_trigger:OverallUpdate-name 'iosapp_version_no' is not defined)
(SyncWorker_19) [custom_components.icloud3.device_tracker] iCloud3 Command Entered, Group: family, Device: maximus_family, Command: event_log <WARN>
(SyncWorker_19) [custom_components.icloud3.device_tracker] Checking Update iCloud Service for family, maximus_family not in this group
```

**Comment by gcobb321** [comment]
Just uploaded a fix for the error message. You should be ok now.

btw-The reason for changing from iosapp2 to iosapp was to support using 
both ios app versions at the same time for different devices. You can 
now use tracking_method: iosapp and if you are tracking several devices, 
one can use v1 while others can use v2 based on the iosapp version 
installed on the device.

------ Original Message ------

**Comment by manonstreet** [comment]
Excellent, thanks.  No more errors.

Not sure if this is an issue or related, but doing a manual refresh in the IOS app used to produce a note about preparing and then I would see the GPS coordinates processed in the icloud3 event log.

With this update, I only see this in the home-assistant.log:
```
(SyncWorker_15) [custom_components.icloud3.device_tracker] iCloud3 Command Entered, Group: family, Device: maximus, Command: event_log <WARN>
(SyncWorker_15) [custom_components.icloud3.device_tracker] Checking Update iCloud Service for family-maximus Processed
(SyncWorker_15) [custom_components.icloud3.device_tracker] iCloud3 Command Processed, Group: family, Device: maximus, Command: event_log . <WARN>
(SyncWorker_18) [custom_components.icloud3.device_tracker] iCloud3 Command Entered, Group: family, Device: maximus, Command: event_log <WARN>
(SyncWorker_18) [custom_components.icloud3.device_tracker] Checking Update iCloud Service for family-maximus Processed
(SyncWorker_18) [custom_components.icloud3.device_tracker] iCloud3 Command Processed, Group: family, Device: maximus, Command: event_log . <WARN>
(SyncWorker_7) [custom_components.icloud3.device_tracker] iCloud3 Command Entered, Group: family, Device: maximus, Command: event_log <WARN>
(SyncWorker_7) [custom_components.icloud3.device_tracker] Checking Update iCloud Service for family-maximus Processed
(SyncWorker_7) [custom_components.icloud3.device_tracker] iCloud3 Command Processed, Group: family, Device: maximus, Command: event_log . <WARN>
```

**Comment by gcobb321** [comment]
I did some cleanup on the event log a while back to standardize the msgs. Some were removed by mistake and were going to be added back but never made it. Saw that one earlier today and will add back tomorrow. Let me see it you see anything else. I’m going to set up the icloud_dev repository greeting for a release. Docs are pretty well done and will also be available for review.

**Comment by manonstreet** [comment]
This issue is starting to wander a bit, so I updated the issue title to match.

I'll look out for the event log fix you noted is coming tomorrow.  As far as I can tell, only 2 other issues remain:

1) The attributes are not populating in the device_tracker.devicename as I noted above.  This previously worked under 1.08b.  These values are being actively updated in the relevant sensors.  For example I can plug my phone in, pull down and refresh on IOS app v2, and sensor.devicename_battery_state will update to "Charging", but the attributes to not show in the device_tracker.

2) I actually saw this same error in 1.08b as well.  Every once in a while I get these errors:
```
ERROR (SyncWorker_11) [custom_components.icloud3.device_tracker] Unable to find service notify/ios_maximus
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 1899, in _polling_loop_15_sec_icloud
    self._request_iosapp_location_update(devicename)
  File "/config/custom_components/icloud3/device_tracker.py", line 2624, in _request_iosapp_location_update
    self.hass.services.call("notify", entity_id, service_data)
  File "/usr/src/homeassistant/homeassistant/core.py", line 1171, in call
    self._hass.loop,
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/src/homeassistant/homeassistant/core.py", line 1208, in async_call
    raise ServiceNotFound(domain, service) from None
homeassistant.exceptions.ServiceNotFound: Unable to find service notify/ios_maximus
ERROR (SyncWorker_11) [custom_components.icloud3.device_tracker] ►ICLOUD/FmF API ERROR, Error=<class 'ValueError'>
ERROR (MainThread) [homeassistant.core] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 1899, in _polling_loop_15_sec_icloud
    self._request_iosapp_location_update(devicename)
  File "/config/custom_components/icloud3/device_tracker.py", line 2624, in _request_iosapp_location_update
    self.hass.services.call("notify", entity_id, service_data)
  File "/usr/src/homeassistant/homeassistant/core.py", line 1171, in call
    self._hass.loop,
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/src/homeassistant/homeassistant/core.py", line 1208, in async_call
    raise ServiceNotFound(domain, service) from None
homeassistant.exceptions.ServiceNotFound: Unable to find service notify/ios_maximus

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/icloud3/device_tracker.py", line 1544, in _polling_loop_5_sec_device
    self._polling_loop_15_sec_icloud(now)
  File "/config/custom_components/icloud3/device_tracker.py", line 1910, in _polling_loop_15_sec_icloud
    self.api.authenticate()           #Reset iCloud
AttributeError: 'NoneType' object has no attribute 'authenticate'
```
As far as I know, when using mobile_app, the notify/ios_devicename no longer works.  Instead we have to use notify/mobile_app_devicename

**Comment by gcobb321** [comment]
Fixed al reported issues, plus a couple of others. While testing, found 
that IOS App does not seem to update the last_changes_time on the 
sensor.<devicename>_last_update_trigger entity when it updates the new 
location via a location update request from iC3. It issues a 'Push 
Notification' trigger but, if the time is not updated, that trigger will 
not be picked up and processed by iC3. Reengineering method of detecting 
change to last_update_request sensor.

Regarding the battery info, that data is no longer on the device_tracker 
entity but in it's own sensor.battery... so iC3 is not looking for the 
info. It is also not available in fmf tracking_method.

Update tomorrow, hopefully.

------ Original Message ------

**Comment by gcobb321** [comment]
I just posted this on the icloud3_dev GitHub Repository. I believe all 
of the items you raised, plus a few others, have been corrected.


iCloud3 v2.0 Release Candidate is now available
This is a major update to iCloud3 with many new features.

Support iCloud tracking methods Find-my-Friends and Family Sharing (2fa 
accounts with notifications and non-2fa accounts without 
notifications)Support HA IOS app tacking method (version 1 & version 
2)iCloud3 Event log Lovelace custom cardMany new attributes & 
sensorsCustomize the list of sensors that are createdTrack devices from 
multiple zonesUpdated and reformatted documentationMany new and updated 
automations, scripts and Lovelace cardsAnd much more…
There are many breaking changes in this release. Be sure to review the 
Change Log in the iCloud3 Documentation

This is the release candidate in the icloud3_dev repository. It will be 
promoted to General Availability on 10/27/2019 if there are no 
unforeseen issues.

Complete documentation with all enhancements and breaking changes can be 
found here <https://gcobb321.github.io/icloud3_dev/#/>Download iCloud3 
v2.0rc here 
<https://github.com/gcobb321/icloud3_dev/releases/tag/2.0rc>The iCloud3 
Development Repository is here <https://github.com/gcobb321/icloud3_dev>

Gary


------ Original Message ------
From: "Gary Cobb" <gcobb321@gmail.com>
To: "gcobb321/icloud3" 
<reply@reply.github.com>
Sent: 10/21/2019 6:18:45 PM
Subject: Re[2]: [gcobb321/icloud3] Multiple errors upgrading from 1.08b 
to 2.0rc (#72)

**Comment by manonstreet** [comment]
Thanks Gary.  I've updated the to the latest code and have some issues to report back.

1)  I'm not sure if this is part of iCloud3, but have a feeling it may be:
```
2019-10-23 20:20:07 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 399, in _async_add_entity
    raise HomeAssistantError(msg)
homeassistant.exceptions.HomeAssistantError: Entity id already exists: sensor.maximus_last_update_trigger. Platform mobile_app does not generate unique IDs
```

2) There is complete breakage between the device tracker created by mobile_app for IOSv2 (in my case device_tracker.maximus_3) and the underlying device_tracker used for identifying zones (in my case device_tracker.maximus).  As per the logs, it appears to be linked properly:

```
2019-10-23 20:20:00 INFO (SyncWorker_4) [custom_components.icloud3.device_tracker] Setting up iCloud3 v2.0rc device tracker for User: <redacted>@gmail.com, Group: family, using device_tracker.legacy code
2019-10-23 20:20:00 INFO (SyncWorker_4) [custom_components.icloud3.device_tracker] Verifying Waze Route Service component
2019-10-23 20:20:00 INFO (SyncWorker_4) [custom_components.icloud3.device_tracker] Waze Settings: Region=US, Realtime=False, MaxDistance=1609.3470878864446, MinDistance=1.6093470878864444
2019-10-23 20:20:00 INFO (MainThread) [homeassistant.setup] Setup of domain mobile_app took 0.3 seconds.
2019-10-23 20:20:00 INFO (SyncWorker_4) [custom_components.icloud3.device_tracker] iCloud3 v2.0rc Initalization > Stage 1, Verify iCloud Location Service
2019-10-23 20:20:00 INFO (SyncWorker_4) [custom_components.icloud3.device_tracker] iCloud3 Tracking Method: IOS App
2019-10-23 20:20:00 INFO (SyncWorker_4) [custom_components.icloud3.device_tracker] iCloud3 v2.0rc Initalization > Stage 2, Setting up tracked devices
2019-10-23 20:20:00 INFO (SyncWorker_4) [custom_components.icloud3.device_tracker] Decoding track_devices <maximus > <redacted>@gmail.com, 3>
2019-10-23 20:20:00 INFO (SyncWorker_4) [custom_components.icloud3.device_tracker] Tracking (IOSApp) > maximus (<redacted>@gmail.com)
2019-10-23 20:20:00 INFO (SyncWorker_4) [custom_components.icloud3.device_tracker] IOS App v2 monitoring > device_tracker.maximus_3, sensor.maximus_last_update_trigger
2019-10-23 20:20:00 INFO (MainThread) [homeassistant.setup] Setup of domain tts took 0.3 seconds.
2019-10-23 20:20:00 INFO (SyncWorker_4) [custom_components.icloud3.device_tracker] Tracking Devices >  maximus (_3)
2019-10-23 20:20:00 INFO (SyncWorker_4) [custom_components.icloud3.device_tracker] iCloud3 v2.0rc Initalization > Stage 3, Setting up maximus
2019-10-23 20:20:00 INFO (MainThread) [homeassistant.components.notify] Setting up notify.mobile_app
2019-10-23 20:20:00 INFO (SyncWorker_4) [custom_components.icloud3.device_tracker] Stationary Zone Created > maximus_stationary
2019-10-23 20:20:00 INFO (SyncWorker_4) [custom_components.icloud3.device_tracker] iCloud3 v2.0rc Initalization > Stage 4, Locating devices
```
However Home Assistant and the iCloud3-event-log is reporting me as 'Home' with my home zone GPS coordinates reported.   And my _3 device tracker populated by mobile_app as well as the native map feature are reporting my real GPS coordinates (1,000+ miles away).

Is there any other information you need to help debug this?

**Comment by gcobb321** [comment]
1. You have the ‘3’ on the track_devices parameter line to track maximus_3. What happens if you leave it off and let iCloud3 scan the entity registry?
2. Comment out iCloud3 so it doesn’t load. go to Developer Tools. Go to States at the top. Scroll down to device _tracker.maximus_3. That is where the location info from the iOS app is picked up by iCloud3. Is it correct? Are there other device trackers.maximus with different sequence numbers? Scroll down and look for sensor.maximus_last_update_trigger. Is there more than one with different numbers? iCloud3 uses that for triggers (zone enter/exit, significant location change and others).
3. Go to Configuration. Go to Integrations. What is the entity name for mobile app maximus? The icons let you change the name on the different sensor created by the iOS app. Find the one for the last _update _trigger. Select it. What is it’s full name with the number, if any? Is there a sensor.last_update_trigger_2 entity?


I’ll try specifying a number on my system tomorrow. I remember seeing that  the entity.py program would try to create an entity if it doesn’t exist when it is referred to a while back. I’m wondering if by you specifying the number on the device tracker line, HA isn’t using the sensor last update trigger for the device tracker entity that exists and trying to create a new one giving the first error message.

If It still gave Errors by removing the ‘3’ on the track devices line,  Put ‘log_level:  debug’ in iCloud3 parameters and let iCloud3 load. Email the complete Home Assistant log file to geekstergary@gmail.com. I’m hoping that will show the location info and any other info tied to the mobile sensors andWhat is going on when it gives the error in entity.py.

 Also, a screen shot of the device tracker States screen and sensor last update trigger screen for maximus might be helpful. And I might want to see the .storage/core.entity_registry file to see how the iOS app set up it’s entities. That is the file that gets scanned to link everything together. By having the _3, you have installed, uninstalled and reinstalled the iOS app several times and I’m wondering if there are residual entries for maximus (_2) getting up picked up by mistake when you put the 3 on the tracked devices line.

You said the location iCloud3 has was home and the iOS app was 1000 miles away. Which is correct?

————————
Gary Cobb

**Comment by gcobb321** [comment]
Two other things:

1. You put a 3 on the track devices parameter to tie it to maximus_3. If you specify it, which I don’t think is needed, it should actually be _3. Perhaps I’ll update iCloud3 to use both.

2. You also don’t need email address since it is iOS app method. Doesn’t hurt but just t used.



————————
Gary Cobb

**Comment by manonstreet** [comment]
1. 
>You have the ‘3’ on the track_devices parameter line to track maximus_3. What happens if you leave it off and let iCloud3 scan the entity registry?

Same result with or without it.  When the "3" was in place, I do believe it was able to identify maximus_3 as indicated in prior the logs:  ```Tracking Devices >  maximus (_3)```.  When removing the email address and the device number (3) such that my config is very basic:
```
- platform: icloud3
  username: !secret icloud_username
  password: !secret icloud_password
  group: family
  tracking_method: iosapp
  track_devices:
    - maximus
```
Everything still appears to be the same as the last time:
```
2019-10-24 08:11:25 INFO (SyncWorker_11) [custom_components.icloud3.device_tracker] Setting up iCloud3 v2.0rc device tracker for User: <redacted>@gmail.com, Group: family, using device_tracker.legacy code
2019-10-24 08:11:25 INFO (SyncWorker_11) [custom_components.icloud3.device_tracker] Verifying Waze Route Service component
2019-10-24 08:11:25 INFO (SyncWorker_11) [custom_components.icloud3.device_tracker] Waze Settings: Region=US, Realtime=False, MaxDistance=1609.3470878864446, MinDistance=1.6093470878864444
2019-10-24 08:11:25 INFO (SyncWorker_11) [custom_components.icloud3.device_tracker] iCloud3 v2.0rc Initalization > Stage 1, Verify iCloud Location Service
2019-10-24 08:11:25 INFO (SyncWorker_11) [custom_components.icloud3.device_tracker] iCloud3 Tracking Method: IOS App
2019-10-24 08:11:25 INFO (SyncWorker_11) [custom_components.icloud3.device_tracker] iCloud3 v2.0rc Initalization > Stage 2, Setting up tracked devices
2019-10-24 08:11:25 INFO (SyncWorker_11) [custom_components.icloud3.device_tracker] Decoding track_devices <maximus>
2019-10-24 08:11:25 INFO (SyncWorker_11) [custom_components.icloud3.device_tracker] Tracking (IOSApp) > maximus (None)
2019-10-24 08:11:25 INFO (SyncWorker_11) [custom_components.icloud3.device_tracker] IOS App v2 monitoring > device_tracker.maximus_3, sensor.maximus_last_update_trigger
2019-10-24 08:11:25 INFO (SyncWorker_11) [custom_components.icloud3.device_tracker] Tracking Devices >  maximus (_3)
2019-10-24 08:11:25 INFO (SyncWorker_11) [custom_components.icloud3.device_tracker] iCloud3 v2.0rc Initalization > Stage 3, Setting up maximus
2019-10-24 08:11:25 INFO (SyncWorker_11) [custom_components.icloud3.device_tracker] Stationary Zone Created > maximus_stationary
2019-10-24 08:11:26 INFO (SyncWorker_11) [custom_components.icloud3.device_tracker] iCloud3 v2.0rc Initalization > Stage 4, Locating devices
2019-10-24 08:11:26 INFO (MainThread) [homeassistant.components.device_tracker] Setting up device_tracker.mobile_app
```
And the same result regarding incorrect location.

2.
>Comment out iCloud3 so it doesn’t load. go to Developer Tools. Go to States at the top. Scroll down to device_tracker.maximus_3. That is where the location info from the iOS app is picked up by iCloud3. Is it correct? 

Even without unloading iCloud3, my information in device_tracker.maximus_3 is correct.

>Are there other device trackers.maximus with different sequence numbers? Scroll down and look for sensor.maximus_last_update_trigger. Is there more than one with different numbers? iCloud3 uses that for triggers (zone enter/exit, significant location change and others).

There is no other device_tracker with sequence numbers.  Just the base "device_tracker.maximus" which iCloud3 is writing its parameters to such as:
```
info: ●Track.Method: IOSApp
trigger: iCloud3@7:50:02
group: family
tracking:  maximus (_3)
icloud3_version: 2.0rc
```

As noted prior, the issue is in reading the correct location data from device_tracker.maximus_3 and populating it into device_tracker.maximus. 

3.
>Go to Configuration. Go to Integrations. What is the entity name for mobile app maximus? The icons let you change the name on the different sensor created by the iOS app. Find the one for the last _update _trigger. Select it. What is it’s full name with the number, if any? Is there a sensor.last_update_trigger_2 entity?

I see that the entity name for the integration is "Unnamed device".  Not sure when that happened. It used to simply be Maximus.  I did update to the latest beta (68) of IOSv2 for compatibility with HA .100+.  Perhaps this caused breakage in the name reporting.  I just set a friendly name to maximus and restarted.  No change.

All entities under the integration were renamed to be consistent with sensor.maximus_<original_name> as per your documentation, including the last_update_trigger.  The only exception here is the device_tracker itself, which I did not rename so it remains as device_tracker.maximus_3.  The device cannot be renamed to drop the _3, because that entity name already exists.  I assume that entity is created via the mobile_app integration when it creates the known_devices.yaml?

I may be making some false assumptions about how things work, so let me restate some things for clarity:
There are 2 device_trackers devices.  There is the base device_tracker.maximus which I assume is what iCloud3 is using as it has special iCloud3 attributes I noted above.  This device shows me as Home with a timestamp of a week ago.

I also have a device_tracker.maximus_3.  This device shows me as Away, and whose GPS coordinates are updated properly every time a refresh the IOS app.  The trouble is that the information from the _3 tracker is not being fed into the base tracker.

As per your other question regarding a stale entity in the .storage/core.entity_registry, I do not see any stale device tracker entities.  I do see a stale device_tracker.maximus_2 in core.restore_state, however the last_seen is 2 weeks ago whereas the device_tracker.maximus_3 last_seen is today.  So I think that may be a red herring.

Do you still need to see the screenshots?

**Comment by manonstreet** [comment]
Another update - it appears to be working now, mostly.  I'm not sure if the original issue was present due to updating the iCloud3 source files while away from my home zone and it needing to get in sync once.  Strange.

Today while exiting my Home zone, the device_tracker.maximus did move to Away, and then to Stationary, and then back to Home properly.  The only thing did not appear to work was a manual refresh once I exited the Stationary zone.  Since I was traveling on the way from from the stationary zone back home, I would have expected it to switch back to Away.  I'll collect more information and report back.

**Comment by manonstreet** [comment]
Changes made to RC5 appear to have fixed all issues.  Thanks Gary!
